### ISSUE TITLE
Talk about AbstractResourceFixture in the docs

### ISSUE THREAD

**Issue by leogout** [Sylius/SyliusFixturesBundle#1]
Hi sylius guys !
I was wondering why is there nothing on `Sylius\Bundle\CoreBundle\Fixture\AbstractResourceFixture` in the docs. Is it because we shouldn't use it in prior of `AbstractFixture`?
If not, should I write some lines on it [here](http://docs.sylius.org/en/latest/bundles/SyliusFixturesBundle/custom_fixture.html) when I'll have some spare time?

**Comment by mamazu** [comment]
The `AbstractResourceFixture` is not part of this bundle. It is part of the main Sylius repository so documentation would belong there.

**Comment by leogout** [comment]
Thank you but it's been four years since I asked this. I'll close the issue.
